### ISSUE TITLE
Releases for unity and windows?

### ISSUE THREAD

**Issue by TheBricktop** [CdecPGL/PlanetaMatchMaker#4]
Hello, thanks for massive amount of work, this is a marvellous networking package,
will it be released soon?

**Comment by CdecPGL** [comment]
Thank you for your interest!

Do you mean you want to obtain an unity package and a binary for windows?
If it is correct, I will build and upload them.

**Comment by TheBricktop** [comment]
Yes, thats what i've meant, couldnt find the unity build that was mentioned in the readme.

**Comment by CdecPGL** [comment]
I understand.
I uploaded the unity package of unity client and the binaries of server to release page.
Please see the link below.

https://github.com/CdecPGL/PlanetaMatchMaker/releases/tag/v0.1.0

It is under development, so there may be some bugs in these packages.
If you find bugs or have any questions, feel free to post issues !
